export const FETCH_PO_REQUESTED = 'FETCH_PO_REQUESTED';
export const FETCH_PO_SUCCEED = 'FETCH_PO_SUCCEED';
export const FETCH_PO_FAILED = 'FETCH_PO_FAILED';
export const CHANGE_ACTIVE_FILTER = 'CHANGE_ACTIVE_FILTER';
