# Generated by Django 2.2 on 2019-04-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreRegisteredTeam',
            new_name='PreRegisteredTeamMember',
        ),
        migrations.RenameField(
            model_name='extenduser',
            old_name='isManager',
            new_name='is_manager',
        ),
    ]
