export const FETCH_NOTES_REQUESTED = 'FETCH_NOTES_REQUESTED';
export const FETCH_NOTES_SUCCEED = 'FETCH_NOTES_SUCCEED';
export const FETCH_NOTES_FAILED = 'FETCH_NOTES_FAILED';
export const ADD_NOTE_REQUESTED = 'ADD_NOTE_REQUESTED';
export const ADD_NOTE_SUCCEED = 'ADD_NOTE_SUCCEED';
export const ADD_NOTE_FAILED = 'ADD_NOTE_FAILED';
